### ISSUE TITLE
代码的一个疑问

### ISSUE THREAD

**Issue by RachelTeamo** [PRIS-CV/FFDI#1]
您好，我想请问一下，在[代码](https://github.com/PRIS-CV/FFDI/blob/master/common/utils.py#L47)中，是不是缺少了对图片低频部分的处理呢？我尝试做了一下可视化，高频部分的没问题，但是低频部分似乎可视化不出来？

**Comment by wangjingyeye** [comment]
> 您好，我想请问一下，在[代码](https://github.com/PRIS-CV/FFDI/blob/master/common/utils.py#L47)中，是不是缺少了对图片低频部分的处理呢？我尝试做了一下可视化，高频部分的没问题，但是低频部分似乎可视化不出来？

我们的代码是先求解低频图像，然后通过：“原图-低频 = 高频” 的方式获得高频，提取低频部分的代码：https://github.com/PRIS-CV/FFDI/blob/77fa09f323adb6dfd212677d6a574a17b31300cf/common/utils.py#L40

**Comment by RachelTeamo** [comment]
感谢您的回复，但是我再可视化 `https://github.com/PRIS-CV/FFDI/blob/77fa09f323adb6dfd212677d6a574a17b31300cf/common/utils.py#L62`中的img_H_temp, i_img_L两个变量时，前者可以正常的可视化（高频部分），而i_img_L似乎不能正常的可视化欸。

**Comment by RachelTeamo** [comment]
> > 您好，我想请问一下，在[代码](https://github.com/PRIS-CV/FFDI/blob/master/common/utils.py#L47)中，是不是缺少了对图片低频部分的处理呢？我尝试做了一下可视化，高频部分的没问题，但是低频部分似乎可视化不出来？
> 
> 我们的代码是先求解低频图像，然后通过：“原图-低频 = 高频” 的方式获得高频，提取低频部分的代码：
> 
> https://github.com/PRIS-CV/FFDI/blob/77fa09f323adb6dfd212677d6a574a17b31300cf/common/utils.py#L40

啊，请问您输入这里的图片对应的格式是[C,H,W],这时候的图片是否已经进行了归一化了呢？还是依然是np.uint8的数据类型呢

**Comment by dongliangchang** [comment]
@wangjingyeye

**Comment by wangjingyeye** [comment]
> 



> Author
